### ISSUE TITLE
Support FairMarketValue raster in NationalDatasets

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/RaveAddIn#104]
Related to this issue:

https://github.com/Riverscapes/riverscapes-tools/issues/113

HEre's the XML

https://github.com/Riverscapes/RiverscapesXML/blob/master/Projects/examples/NationalDatasets.xml#L65-L68

**Comment by joewheaton** [comment]
We do need the symbology. I have created the layer file I want here: [`FairMarketValue.lyr`](https://usu.box.com/s/zxpm5ial4ce6zom5syedv8ojng7j5cbj).

However, the symbology I want is for an updated version of this where the Units are *$ per hectare* instead of *log $ per hectare*.  It looks nice:

![image](https://user-images.githubusercontent.com/9723905/105614692-1ee21300-5d88-11eb-861a-45a0dc817bd5.png)
