### ISSUE TITLE
HTML Redirect from https://rave.riverscapes.net to https://viewer.riverscapes.net

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/RaveAddIn#189]
We should (@philipbaileynar) fix all the old rave links to viewer links (https://rave.riverscapes.net to https://viewer.riverscapes.net), but short of that, we will NOT catch them all. Please put redirect in place.

**Comment by MattReimer** [comment]
I've done this but the domain may not roll over properly for a few hours.

BTW This is a more complex process since we moved our DNS to Route53 from Gandi. It means creating empty S3 buckets with static web hosting enabled for every redirect we want:

https://repost.aws/knowledge-center/redirect-domain-route-53

**Comment by MattReimer** [comment]
Update. This won't work for HTTPS redirects. I'm looking for a new solution

**Comment by MattReimer** [comment]
Ok. I think I've got it now. 

@joewheaton same notes as before. Close this issue when the redirect works for you.

Fot my own notes, this is the new process for implementing a single web redirect (because I keep forgetting):

1. Make an S3 bucket named as the old URL `rave.riverscapes.net` with web hosting redirection enabled that points to the address you want to redirect to `viewer.riverscapes.net`
2. Put a file called `DON'T DELETE ME, I'M A REDIRECT.TXT` in the bucket so you don't accidentally delete it later when you're auditing buckets.
3. Create a new AWS SSL certificate and associated CNAME verification record in Route53 (this we should be able to re-use as long as it's a `*.riverscapes.net` domain repoint
4. Create a Cloudfront web distribution that uses the SSL cert and points to the S3 bucket's web hosting endpoint
5. Create an A record on Route53 that points to the Cloudfront web distribution. 


@joewheaton

**Comment by joewheaton** [comment]
![Screenshot_20240130-193559.png](https://github.com/Riverscapes/RaveAddIn/assets/9723905/3052d5d7-dfa2-4a72-9c16-b2c9345216f4)

**Comment by MattReimer** [comment]
yup. still broken. I'll take another swing

**Comment by joewheaton** [comment]
Worked for me now! Thanks @MattReimer
