### ISSUE TITLE
Layer Transparency

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/RaveAddIn#5]
Layer transparency is not being applied when adding items to the map.

I suspect that the code is picking up the symbology renderer from the layer file but not looking for other properties stored in the layer file that might be applied to the layer over all, such as the transparency.

**Comment by joewheaton** [comment]
If we end up going to [`.qml`](https://doc.qt.io/archives/qt-4.8/qdeclarativebasictypes.html), instead of `.lyr`, layer transparency is controlled with the `alpha` argument. See [this post](https://gis.stackexchange.com/questions/184026/is-it-possible-to-edit-layer-transparency-in-sld-or-qml-file-for-use-in-qgis)
